---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep2
  labels:
    task: two
    tier: homework
  annotations:
    container: nginx
    container-init: busybox
  namespace: netology-2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4
      initContainers:
        - name: busybox
          image: busybox:1.36.1
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "8Mi"
              cpu: "50m"
          env:
            - name: TARGET
              value: "svc2"
          command: ['sh', '-c', "until nslookup $TARGET.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do sleep 2; done"]
...