---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: netology-2
spec:
  selector:
    app: nginx-init
  type: ClusterIP
  ports:
    - name: nginx
      port: 8888
      targetPort: 80
...